### ISSUE TITLE
Docs: Mention rust dependency

### ISSUE THREAD

**Issue by chrisgrieser** [napisani/nvim-github-codesearch#1]
![CleanShot 2023-04-17 at 22 12 02@2x](https://user-images.githubusercontent.com/73286100/232599457-030cce37-7681-47a9-bb6b-e729b1cb46f9.png)

I am guessing you need cargo installed for this to work?

edit: yes, it looks like it

**Comment by napisani** [comment]
Thank you for pointing this out, in the future Im hoping to provide prebuilt dylibs instead of needing to build them from source.
But im waiting for this cargo-dist feature to be implemented https://github.com/axodotdev/cargo-dist/issues/179

Until then, I added a small dependency disclaimer section to the bottom of the readme.
Im sorry for the trouble.
